### PR TITLE
[Technical Support] LPS-72761 Using bad portlet id in frontend-editor-alloyeditor-web module

### PR DESCRIPTION
**Pull request by zsagia**
Hi Dustin,

Please keep in mind this fix depends on LPS-73343. As I wanted to write you yesterday if my fix would be correct I'm going to open more tickets with the same issue. I think in portal code where we use this pattern and the portlet is instancable we need to fix them.

Thanks,
 Zsaga

### CODE REVIEW

**Comment by dustinryerson** [comment]
Waiting on https://github.com/liferay/com-liferay-dynamic-data-mapping/pull/298

**Comment by gregory-bretall** [comment]
Resent to https://github.com/Robert-Frampton/com-liferay-frontend-editor/pull/1

**Comment by zsigmondrab** [comment]
See https://github.com/Robert-Frampton/com-liferay-frontend-editor/pull/1?#issuecomment-318360324

**Comment by gregory-bretall** [comment]
Merged here https://github.com/brianchandotcom/liferay-portal/compare/baae41817d...051950dc76

**Pull request closed without merging**
